# 📘 KG course SPARQL notebook

A notebook to run SPARQL queries for the KG course at UM DACS.

1. Update the `g.parse()` calls in the first cell to import your RDF files.
2. In the same folder as the notebook create files with your SPARQL queries (e.g. `q1.rq`), and execute them with `run_query(g, 'q1.rq')`

Use the `.rq` file extension to get SPARQL syntax coloration

In [1]:
import sys
!pip install pandas oxrdflib Pygments rdflib

import pandas as pd
from IPython.display import display, HTML
from pygments import highlight
from pygments.lexers import SparqlLexer
from pygments.formatters import HtmlFormatter
from rdflib import Graph

Requirement already satisfied: pandas in C:\Users\Pc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.3.3)
Requirement already satisfied: oxrdflib in C:\Users\Pc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.5.0)
Requirement already satisfied: Pygments in C:\Users\Pc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.19.2)
Requirement already satisfied: rdflib in C:\Users\Pc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (7.5.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Pc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Pc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Pc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Pc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: pyoxigraph~=0.5.0 in C:\Users\Pc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from oxrdflib) (0.5.5)
Requirement already satisfied: pyparsing<4,>=2.1.0 in C:\Users\Pc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rdflib) (3.2.5)
Requirement already satisfied: six>=1.5 in C:\Users\Pc\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:

def run_query(graph, query_path):
    try:
        with open(query_path, 'r') as file:
            query = file.read()
    except Exception as _e:
        print(f"No file for {query_path}")
        return
    results = graph.query(query)
    # Display the SPARQL query
    formatted_query = highlight(query, SparqlLexer(), HtmlFormatter(style='solarized-dark', full=True, nobackground=True))
    display(HTML(formatted_query))
    # Convert results to a Pandas DataFrame
    res_list = []
    for row in results:
        res_list.append([str(item) for item in row])
    df = pd.DataFrame(res_list, columns=[str(var) for var in results.vars]) if len(res_list) > 0 else pd.DataFrame()
    # Display the DataFrame as a table in Jupyter Notebook
    display(HTML(df.to_html()))

g = Graph(store="Oxigraph")

# TODO: modify/add paths to your RDF files
g.parse("./food_kg.ttl")

print(f"Working with {len(g)} triples")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Pc\\Documents\\GitHub\\food_kg.ttl'

1. Identify one type of quality check different than above, write and run SPARQL to implement the check and return the violating entities.

In [49]:
run_query(g, 'q1.rq')

2. Identify a second type of quality check different than above, write and run SPARQL to implement the check and return the violating entities.

In [50]:
run_query(g, 'q2.rq')
#this returns nothing because none of the

3. Identify a third type of quality check different than above, write and run SPARQL to implement the check and return the violating entities.

In [51]:
run_query(g, 'q3.rq')

4. Identify a forth type of quality check different than above, write and run SPARQL to implement the check and return the violating entities.

In [52]:
run_query(g, 'q4.rq')

5. Identify a fifth type of quality check different than above, write and run SPARQL to implement the check and return the violating entities.

In [53]:
run_query(g, 'q5.rq')

6. Identify a sixth type of quality check different than above, write and run SPARQL to implement the check and return the violating entities.

In [54]:
run_query(g, 'q6.rq')

No file for q6.rq

7. Identify a seventh type of quality check different than above, write and run SPARQL to implement the check and return the violating entities.

In [55]:
run_query(g, 'q7.rq')

No file for q7.rq

8. Identify an eighth type of quality check different than above, write and run SPARQL to implement the check and return the violating entities.

In [56]:
run_query(g, 'q8.rq')

No file for q8.rq

9. Identify a seventh type of quality check different than above, write and run SPARQL to implement the check and return the violating entities.

In [57]:
run_query(g, 'q9.rq')

No file for q9.rq

10. Identify a final type of quality check different than above, write and run SPARQL to implement the check and return the violating entities.

In [58]:
run_query(g, 'q10.rq')

No file for q10.rq